#!/bin/bash

set -eux

RLY="${RLY_BIN} --debug"
PATH_NAME=ibc01

$RLY tx clients $PATH_NAME
sleep 3
$RLY lcp activate-client $PATH_NAME --src=true
$RLY lcp activate-client $PATH_NAME --src=false
$RLY tx connection $PATH_NAME -o 2s
$RLY tx channel $PATH_NAME -o 2s
