#!/bin/bash
set -eux

RLY="${RLY_BIN} --debug"
TEST_DIR=$(dirname $(dirname $(dirname "$0")))

echo "src -> dst: send packet"
source ${TEST_DIR}/chain0.env.sh
npx hardhat --network chain0 send-packet \
    --mockapp ${IBC_MOCKAPP} \
    --message "mock packet data" \
    --port mockapp \
    --channel channel-0 \
    --timeoutheight 1000000000

sleep 4
echo "src -> dst: relay packet"
${RLY} tx relay ibc01
echo "src -> dst: ack packet"
sleep 4
${RLY} tx acks ibc01

echo "dst -> src: send packet"
source ${TEST_DIR}/chain1.env.sh
npx hardhat --network chain1 send-packet \
    --mockapp ${IBC_MOCKAPP} \
    --message "mock packet data" \
    --port mockapp \
    --channel channel-0 \
    --timeoutheight 1000000000

sleep 4
echo "dst -> src: relay packet"
${RLY} tx relay ibc01
sleep 4
echo "dst -> src: ack packet"
${RLY} tx acks ibc01
