name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@nightly
      - uses: datachainlab/rust-cache@allow_registry_src_caching
      - run: cargo test
      - run: make fmt
      - run: make lint-tools
      - run: make lint

  e2e-test:
    needs: test
    runs-on: ubuntu-22.04
    env:
      SGX_MODE: SW
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: e2e/relayer/go.mod
          cache-dependency-path: |
            e2e/relayer/go.sum
      - uses: dtolnay/rust-toolchain@nightly
      - uses: datachainlab/rust-cache@allow_registry_src_caching
        with:
          workspaces: |
            ./e2e/lcp
            ./e2e/enclave
          cache-directories: |
            ~/.cargo/registry/src/**/librocksdb-sys-*
      - run: curl -LO https://download.01.org/intel-sgx/sgx-linux/2.19/distro/ubuntu22.04-server/sgx_linux_x64_sdk_2.19.100.3.bin
      - run: chmod +x ./sgx_linux_x64_sdk_2.19.100.3.bin
      - run: echo -e 'no\n/opt' | ./sgx_linux_x64_sdk_2.19.100.3.bin
      - run: cd ./e2e && npm install
      - run: |
          sed -i "s/#user:/user: \"$(id -u):$(id -g)\"/g" ./e2e/compose.yml
      - run: source /opt/sgxsdk/environment && make -C e2e e2e-test
